# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/dawid/poky-rpi/meta \
  /home/dawid/poky-rpi/meta-poky \
  /home/dawid/poky-rpi/meta-yocto-bsp \
  /home/dawid/poky-rpi/meta-raspberrypi \
  /home/dawid/poky-rpi/meta-openembedded/meta-oe \
  /home/dawid/poky-rpi/meta-openembedded/meta-python \
  /home/dawid/poky-rpi/meta-qt6 \
  /home/dawid/poky-rpi/meta-dawid \
  "
