# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-dawid"
BBFILE_PATTERN_meta-dawid = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-dawid = "6"

LAYERDEPENDS_meta-dawid = "core"
LAYERSERIES_COMPAT_meta-dawid = "scarthgap"
